// Generated by CoffeeScript 1.10.0
(function() {
  var _, createElement, defaultOptions, jsdom, pd;

  jsdom = require('jsdom');

  _ = require('underscore');

  pd = require('pretty-data').pd;

  defaultOptions = {
    filename: null,
    callback: function(d) {},
    xlink: true
  };

  createElement = function(window) {
    var body, doc, svg;
    doc = window.document;
    svg = doc.createElement('svg');
    body = doc.querySelector('body');
    body.appendChild(svg);
    svg.setAttribute('xmlns', 'http://www.w3.org/2000/svg');
    return svg;
  };

  module.exports = function(processor, options, callback) {
    _.defaults(options, defaultOptions);
    if (callback === null) {
      callback = options.callback;
    }
    return jsdom.env({
      html: '<html><body></body></html>',
      features: {
        QuerySelector: true
      },
      done: function(err, window) {
        var a, fs, svg;
        global.window = window;
        svg = createElement(window, processor);
        if (options.xlink) {
          svg.setAttribute('xmlns:xlink', 'http://www.w3.org/1999/xlink');
        }
        processor(svg, window);
        a = jsdom.serializeDocument(svg).replace(/clippath/g, 'clipPath').replace(/textpath/g, 'textPath').replace(/textarea/g, 'textArea');
        if (options.xlink) {
          a = a.replace(/href/g, 'xlink:href');
        }
        a = pd.xml(a);
        if (options.filename === null) {
          return callback(a);
        } else {
          fs = require('fs');
          fs.writeFileSync(options.filename, a);
          return callback();
        }
      }
    });
  };

}).call(this);
